import type { Trip, Sport } from "./types";

export const TRIPS: Trip[] = [
  {
    id: "barcelone",
    city: "Barcelone",
    country: "Espagne",
    coords: [41.3874, 2.1686],
    desc: "Séjour en Catalogne.",
    photos: ["/images/interets/barcelone-1.jpg"],
  },
  {
    id: "newyork",
    city: "New York",
    country: "USA",
    coords: [40.7128, -74.006],
    desc: "New-York : 'Empire State of Mind'.",
    photos: [
      "/images/interets/newyork-1.jpg",
      "/images/interets/newyork-2.jpg",
      "/images/interets/newyork-3.jpg", 
    ],
  },
  {
    id: "montreal",
    city: "Montréal",
    country: "Canada",
    coords: [45.5017, -73.5673],
    desc: "Immersion culturelle.",
    photos: [
      "/images/interets/montreal-1.jpg",
      "/images/interets/montreal-2.jpg",
      "/images/interets/montreal-3.jpg",
    ],
  },
  {
    id: "bruxelles",
    city: "Bruxelles",
    country: "Belgique",
    coords: [50.8503, 4.3517],
    desc: "Meilleur chocolat et gaufres.",
    photos: [
      "/images/interets/bruxelles-1.jpg",
      "/images/interets/bruxelles-2.jpg",
      "/images/interets/bruxelles-3.jpg",
    ],
  },
  {
    id: "parcprinces",
    city: "Parc des Princes",
    country: "France",
    coords: [48.8414, 2.253],
    desc: "Ici c'est Paris (PSG).",
    photos: [
      "/images/interets/parcdesprinces-0.jpg",
      "/images/interets/parcdesprinces-1.jpg",
      "/images/interets/parcdesprinces-2.jpg",
    ],
  },
  {
    id: "seattle",
    city: "Seattle",
    country: "USA",
    coords: [47.6062, -122.3321],
    desc: "Nord-ouest américain.",
    photos: [
      "/images/interets/seattle-1.jpg",
      "/images/interets/seattle-2.jpg",
    ],
  },
  {
    id: "sanfrancisco",
    city: "San Francisco",
    country: "USA",
    coords: [37.7749, -122.4194],
    desc: "Golden Gate Bridge.",
    photos: [
      "/images/interets/sanfrancisco-1.jpg",
      "/images/interets/sanfrancisco-2.jpg",
      "/images/interets/sanfrancisco-3.jpg",
    ],
  },
  {
    id: "malaga",
    city: "Malaga",
    country: "Espagne",
    coords: [36.7213, -4.4214],
    desc: "Plages et soleil.",
    photos: [
      "/images/interets/malaga-1.jpg",
      "/images/interets/malaga-2.jpg",
      "/images/interets/malaga-3.jpg",
    ],
  },
  {
    id: "seville",
    city: "Séville",
    country: "Espagne",
    coords: [37.3891, -5.9845],
    desc: "Plaza de España.",
    photos: [
      "/images/interets/seville-1.jpg",
      "/images/interets/seville-2.jpg",
      "/images/interets/seville-3.jpg",
    ],
  },
  {
    id: "niagara",
    city: "Chutes du Niagara",
    country: "USA",
    coords: [43.0962, -79.0377],
    desc: "Côté américain.",
    photos: [
      "/images/interets/niagara-1.jpg",
      "/images/interets/niagara-2.jpg",
      "/images/interets/niagara-3.jpg",
    ],
  },
  {
    id: "gibraltar",
    city: "Gibraltar",
    country: "Gibraltar",
    coords: [36.1408, -5.3536],
    desc: "Territoire britannique.",
    photos: [
      "/images/interets/gibraltar-1.jpg",
      "/images/interets/gibraltar-2.jpg",
    ],
  },
  {
    id: "bordeaux",
    city: "Bordeaux",
    country: "France",
    coords: [44.8378, -0.5792],
    desc: "Place de la Bourse et Cité du Vin.",
    photos: [
      "/images/interets/bordeaux-1.jpg",
      "/images/interets/bordeaux-2.jpg",
    ],
  },
  {
    id: "collioure",
    city: "Collioure",
    country: "France",
    coords: [42.5263, 3.082],
    desc: "Village catalan.",
    photos: [
      "/images/interets/collioure-1.jpg",
      "/images/interets/collioure-2.jpg",
    ],
  },
  {
    id: "londres",
    city: "Londres",
    country: "Angleterre",
    coords: [51.5074, -0.1278],
    desc: "Séjour étudiant 2022.",
    photos: [
      "/images/interets/londres-1.jpg",
      "/images/interets/londres-2.jpg",
      "/images/interets/londres-3.jpg",
      "/images/interets/londres-4.jpg",
      "/images/interets/londres-5.jpg",
    ],
  },
  {
    id: "harvard",
    city: "Harvard",
    country: "USA",
    coords: [42.377, -71.1167],
    desc: "Campus mythique.",
    photos: [
      "/images/interets/harvard-1.jpg",
      "/images/interets/harvard-2.jpg",
      "/images/interets/harvard-3.jpg",
    ],
  },
  {
    id: "fortboyard",
    city: "Fort Boyard",
    country: "France",
    coords: [45.996, -1.25],
    desc: "Tour en bateau.",
    photos: ["/images/interets/fortboyard.jpg"],
  },
  {
    id: "eirandonan",
    city: "Eilean Donan Castle",
    country: "Écosse",
    coords: [57.2737, -5.5161],
    desc: "Château iconique.",
    photos: ["/images/interets/ecosse-eileandonancastle.jpg"],
  },
  {
    id: "lochness",
    city: "Loch Ness",
    country: "Écosse",
    coords: [57.3249, -4.4401],
    desc: "Urquhart Castle.",
    photos: ["/images/interets/ecosse-lochnessurquhartcastle.jpg"],
  },
  {
    id: "losangeles",
    city: "Los Angeles",
    country: "USA",
    coords: [34.0522, -118.2437],
    desc: "Hollywood Vibe.",
    photos: [
      "/images/interets/losangeles-1.jpg",
      "/images/interets/losangeles-2.jpg",
    ],
  },
  {
    id: "lewarde",
    city: "Lewarde",
    country: "France",
    coords: [50.3317869, 3.1707202],
    desc: "Centre minier.",
    photos: [
      "/images/interets/lewarde-1.jpg",
      "/images/interets/lewarde-2.jpg",
    ],
  },
  {
    id: "pierremauroy",
    city: "Stade Pierre Mauroy",
    country: "France",
    coords: [50.611, 3.13],
    desc: "Match du LOSC.",
    photos: [
      "/images/interets/pierremauroy-1.jpg",
      "/images/interets/pierremauroy-2.jpg",
      "/images/interets/pierremauroy-3.jpg",
    ],
  },
  {
    id: "toulouse",
    city: "Toulouse",
    country: "France",
    coords: [43.6045, 1.444],
    desc: "La ville rose.",
    photos: [
      "/images/interets/toulouse-1.jpg",
      "/images/interets/toulouse-2.jpg",
    ],
  },
  {
    id: "toulon",
    city: "Toulon",
    country: "France",
    coords: [43.1242, 5.928],
    desc: "Randonnée.",
    photos: [
      "/images/interets/toulon-1.jpg",
      "/images/interets/toulon-2.jpg",
    ],
  },
  {
    id: "hyeres",
    city: "Hyères",
    country: "France",
    coords: [43.1204, 6.1286],
    desc: "Îles d’or.",
    photos: [
      "/images/interets/hyeres-1.jpg",
      "/images/interets/hyeres-2.jpg",
      "/images/interets/hyeres-3.jpg",
    ],
  },
];

export const SPORTS: Sport[] = [
  {
    id: "karate",
    title: "Karaté",
    desc: "Sport qui m'a enseigné la discipline, la confiance en soi et le respect ; pratiqué de mes 7 ans à mes 18 ans.",
    photos: ["/images/interets/sport-4.jpg"],
  },
  {
    id: "football",
    title: "Football",
    desc: "Supporter du PSG, pratique en FSGT (amical) et en club à l'Étoile Sportive de Paris.",
    photos: [
      "/images/interets/soccer-1.jpg",
      "/images/interets/soccer-2.jpg",
      "/images/interets/soccer-3.jpg",
    ],
  },
  {
    id: "escalade",
    title: "Escalade",
    desc: "Passion familiale pratiquée à quelques occasions (colonie, Club Familial de Condé).",
    photos: ["/images/interets/sport-1.jpg"],
  },
  {
    id: "design",
    title: "Design & Création",
    desc: "Compte professionnel Instagram de Design sur la thématique du Sport (DesignFlex&Sport). <br /><a href='https://www.instagram.com/designflexsport/' target='_blank' rel='noreferrer'>Lien du compte</a>",
    photos: [
      "/images/interets/design-1.png",
      "/images/interets/design-2.png",
      "/images/interets/design-3.png",
    ],
  },
];
